// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package events

import (
	"errors"
	"fmt"
)

const (
	// EventTypeCreateOrder is a EventType of type CreateOrder.
	EventTypeCreateOrder EventType = "CreateOrder"
	// EventTypeCancelOrder is a EventType of type CancelOrder.
	EventTypeCancelOrder EventType = "CancelOrder"
	// EventTypeMatching is a EventType of type Matching.
	EventTypeMatching EventType = "Matching"
)

var ErrInvalidEventType = errors.New("not a valid EventType")

// String implements the Stringer interface.
func (x EventType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventType) IsValid() bool {
	_, err := ParseEventType(string(x))
	return err == nil
}

var _EventTypeValue = map[string]EventType{
	"CreateOrder": EventTypeCreateOrder,
	"CancelOrder": EventTypeCancelOrder,
	"Matching":    EventTypeMatching,
}

// ParseEventType attempts to convert a string to a EventType.
func ParseEventType(name string) (EventType, error) {
	if x, ok := _EventTypeValue[name]; ok {
		return x, nil
	}
	return EventType(""), fmt.Errorf("%s is %w", name, ErrInvalidEventType)
}

// MarshalText implements the text marshaller method.
func (x EventType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventType) UnmarshalText(text []byte) error {
	tmp, err := ParseEventType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// OrderTypeBuy is a OrderType of type Buy.
	OrderTypeBuy OrderType = iota
	// OrderTypeSell is a OrderType of type Sell.
	OrderTypeSell
)

var ErrInvalidOrderType = errors.New("not a valid OrderType")

const _OrderTypeName = "BuySell"

var _OrderTypeMap = map[OrderType]string{
	OrderTypeBuy:  _OrderTypeName[0:3],
	OrderTypeSell: _OrderTypeName[3:7],
}

// String implements the Stringer interface.
func (x OrderType) String() string {
	if str, ok := _OrderTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("OrderType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x OrderType) IsValid() bool {
	_, ok := _OrderTypeMap[x]
	return ok
}

var _OrderTypeValue = map[string]OrderType{
	_OrderTypeName[0:3]: OrderTypeBuy,
	_OrderTypeName[3:7]: OrderTypeSell,
}

// ParseOrderType attempts to convert a string to a OrderType.
func ParseOrderType(name string) (OrderType, error) {
	if x, ok := _OrderTypeValue[name]; ok {
		return x, nil
	}
	return OrderType(0), fmt.Errorf("%s is %w", name, ErrInvalidOrderType)
}

// MarshalText implements the text marshaller method.
func (x OrderType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *OrderType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseOrderType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
