// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package events

import (
	"errors"
	"fmt"
)

const (
	// EventTypeCreateOrder is a EventType of type CreateOrder.
	EventTypeCreateOrder EventType = "CreateOrder"
	// EventTypeCancelOrder is a EventType of type CancelOrder.
	EventTypeCancelOrder EventType = "CancelOrder"
	// EventTypeMatching is a EventType of type Matching.
	EventTypeMatching EventType = "Matching"
)

var ErrInvalidEventType = errors.New("not a valid EventType")

// String implements the Stringer interface.
func (x EventType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventType) IsValid() bool {
	_, err := ParseEventType(string(x))
	return err == nil
}

var _EventTypeValue = map[string]EventType{
	"CreateOrder": EventTypeCreateOrder,
	"CancelOrder": EventTypeCancelOrder,
	"Matching":    EventTypeMatching,
}

// ParseEventType attempts to convert a string to a EventType.
func ParseEventType(name string) (EventType, error) {
	if x, ok := _EventTypeValue[name]; ok {
		return x, nil
	}
	return EventType(""), fmt.Errorf("%s is %w", name, ErrInvalidEventType)
}

// MarshalText implements the text marshaller method.
func (x EventType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventType) UnmarshalText(text []byte) error {
	tmp, err := ParseEventType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
